# Recurring job configuration
# See: https://github.com/rails/solid_queue/tree/main/docs/recurring

# Default configuration to be inherited
default: &default
  schedule_prompt_activation:
    class: SchedulePromptActivationJob
    queue: default
    schedule: at 12am every day

# Development environment configuration
development:
  <<: *default

# Production environment configuration  
production:
  <<: *default
