# Recurring job configuration
# See: https://github.com/rails/solid_queue/tree/main?tab=readme-ov-file#recurring-tasks

# Default configuration to be inherited
default: &default
  schedule_daily_prompt_activations:
    class: ScheduleDailyPromptActivationsJob
    queue: default
    schedule: every day at 12AM
  schedule_prompt_creation_nudges:
    class: SchedulePromptCreationNudgesJob
    queue: default
    schedule: every day at 12AM
  notify_about_recent_posts:
    class: NotifyAboutRecentPostsJob
    queue: default
    schedule: "30 6-23/2 * * *"

# Development environment configuration
development:
  <<: *default

# Production environment configuration
production:
  <<: *default
